// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType } from 'typesafe-i18n'
import type { LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = {
	/**
	 * Welcome to Svelte Fall Summit 2021
	 */
	'HI': string
}

export type TranslationFunctions = {
	/**
	 * Welcome to Svelte Fall Summit 2021
	 */
	'HI': () => LocalizedString
}

export type Formatters = {}
